### ISSUE TITLE
Crash at "getting noise profile"

### ISSUE THREAD

**Issue by bwang482** [cplaguna-audio/REPAIR#1]
Hi thanks for the great app. 

I have been using it for declipping my audios. However for some longer audios (~40mins), the app always crash at "getting noise profile" stage. Is there anyway I can do about this? Please help witht his thanks!!!

**Comment by cplaguna-audio** [comment]
Hello,

Thanks for the interest in this project! I’m happy if it is able to be of use. This was my Master’s project which I completed in 2016 and have not been maintaining, so unfortunately you’ll have to live with whatever state it’s currently in (I’m somewhat surprised it is still working at all!)

One option is to split your audio file into smaller segments, declip the smaller segments, and then recombine the segments into the larger file. To split and recombine an audio file, one option (there are many ways to do this) is to use Audacity (https://www.audacityteam.org/), which is free.

Otherwise I would suggest a declipping or audio restoration VST, I think Izotope RX is one of the industry standards for audio restoration (you might be able to buy the declipping module separately to make it cheaper). There may be free declipping vsts out there if you explore.

Hope this helps,
Chris

From: bluemonk482
Sent: Thursday, April 23, 2020 6:13 PM
To: cplaguna-audio/REPAIR
Cc: Subscribed
Subject: [cplaguna-audio/REPAIR] Crash at "getting noise profile" (#1)

Hi thanks for the great app.
I have been using it for declipping my audios. However for some longer audios (~40mins), the app always crash at "getting noise profile" stage. Is there anyway I can do about this? Please help witht his thanks!!!

**Comment by bwang482** [comment]
Thanks for your reply @cplaguna-audio ! Appreciated! That's very helpful. I shall close the issue now.
